version: 0.2

phases:
  pre_build:
    commands:
      - echo "No Prebuild......"
    commands:
      - mvn clean install dependency-check:check
      - mv target/dependency-check-reports reports/
      - zip -r my-artifact.zip reports/
      - mvn clean install
artifacts:
  files: my-artifact.zip
