version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon CodeArtifact... 
      - cp ./settings.xml /root/.m2/settings.xml #This is must thing for getting packages from codeartifacts 
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain owaps --domain-owner 175662053988 --region us-east-1 --query authorizationToken --output text`
  build:
    commands:
      - mvn clean install dependency-check:check
      - mv target/dependency-check-reports reports/
      - zip -r my-artifact.zip reports/
      - mvn clean install
artifacts:
  files: my-artifact.zip
