version: 0.2

phases:
  pre_build:
    commands:
      - echo "No Prebuild......"
  build:
    commands:
      - mvn clean install dependency-check:check
      - mv target/dependency-check-reports reports/
      - TIMESTAMP=$(date +'%Y%m%d%H%M%S')
      - zip -r owasp-report-${TIMESTAMP}.zip reports/
      - mvn clean install

artifacts:
  files: owasp-report-*.zip
