version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y maven

  build:
    commands:
      - echo "Building project..."
      - mvn clean install

  post_build:
  commands:
    - echo "Running OWASP Dependency-Check..."
    - mvn dependency-check:check

artifacts:
  files: 
    - target/dependency-check-report.html
    # Add other artifacts as needed

  # Specify the S3 bucket and object key where you want to store the report
  s3:
    bucket: sarvar-devops
    path: OWASP/
    # Other S3 configuration options if needed
