version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting up CodeArtifact credentials..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain test --domain-owner 175662053988 --region us-east-1 --query authorizationToken --output text)
      - aws codeartifact login --repository artifacts --domain test --authorization-token $CODEARTIFACT_AUTH_TOKEN

  build:
    commands:
      - echo "Building project..."
      - mvn clean install

artifacts:
  files: 
    - target/*  # or specify the artifacts you want to include
    # Add other artifacts as needed

  # Specify CodeArtifact as the target
  codeartifact:
    repository: artifacts
    domain: test
    target: /  # Target path within the repository

  # Optionally, you can add additional CodeArtifact configuration options if needed
